### ISSUE TITLE
lot of errors after new installation 

### ISSUE THREAD

**Issue by zesa0000** [munkireport/munkireport-php#1054]
until now i was using munkireport 2.x
now munkireport 3.x makes any troubles...

after all configs and installation, i get these errors and I dont know, what the problem is:

```
Setting preferences
Installation of MunkiReport v3.1.1 complete.
Running the preflight script for initialization
    Munkireport: # Executing scripts in preflight_abort.d
    Munkireport: # Executing scripts in preflight.d
    Munkireport: Running submit.preflight
    Munkireport: submit.preflight Error: ERROR: Munkireport: Could not unserialize server data: Next is `b` not `:` in ...<b --> r <--  />
<b>Fatal error</b>:  Uncaught PDOException: S...
ERROR: Munkireport: Request: {'items': 'a:2:{s:7:"machine";a:1:{s:4:"hash";s:32:"e9d5e6f487a70b0368acb826f1863351";}s:10:"reportdata";a:1:{s:4:"hash";s:32:"7e0a03f49e96b118dfa1696aea5564ba";}}', 'serial': u'CCCCCC', 'passphrase': u'11012419-D549-4267-EAB4-319D85986F56'}
ERROR: Munkireport: Response: <br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: machine_group in /media/munkireport-php/system/kissmvc_core.php:459
Stack trace:
#0 /media/munkireport-php/system/kissmvc_core.php(459): PDO-&gt;prepare('SELECT * FROM `...', Array)
#1 /media/munkireport-php/system/kissmvc_core.php(602): KISS_Model-&gt;prepare('SELECT * FROM `...')
#2 /media/munkireport-php/app/helpers/site_helper.php(217): KISS_Model-&gt;retrieveOne('property=? AND ...', Array)
#3 /media/munkireport-php/app/controllers/report.php(31): passphrase_to_group('11012419-D549-4...')
#4 /media/munkireport-php/system/kissmvc_core.php(82): munkireport\controller\report-&gt;__construct()
#5 /media/munkireport-php/system/kissmvc.php(17): KISS_Engine-&gt;__construct(Array, 'show', 'index', 'AUTO')
#6 /var/www/html/index.php(147): Engine-&gt;__construct(Array, 'show', 'index', 'AUTO')
#7 {main}
  thrown in <b>/media/munkireport-php/system/kissmvc_core.php</b> on line <b>459</b><br />
```

what is the problem?
munkireport shows me on the firstpage:
Request Failed: parsererror, SyntaxError: Unexpected token < in JSON at position 0

:/

**Comment by bochoven** [comment]
Please read the munkireport wiki on how to migrate to v3, especially the part about the new db config
