### ISSUE TITLE
Providing a SITENAME with spaces for docker via env_file causes error

### ISSUE THREAD

**Issue by nathanperkins** [munkireport/munkireport-php#1221]
When I provide a sitename in a docker env_file like this:

```
SITENAME=Mac Reporting
```

trying to navigate to any page gives this error:

```
Fatal error: Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php:262 Stack trace: #0 /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php(146): Dotenv\Loader->sanitiseVariableValue('SITENAME', 'Mac Reporting') #1 /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php(125): Dotenv\Loader->processFilters('SITENAME', 'Mac Reporting') #2 /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php(365): Dotenv\Loader->normaliseEnvironmentVariable('SITENAME=Mac Re...', NULL) #3 /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php(88): Dotenv\Loader->setEnvironmentVariable('SITENAME=Mac Re...') #4 /var/munkireport/vendor/vlucas/phpdotenv/src/Dotenv.php(106): Dotenv\Loader->load() #5 /var/munkireport/vendor/vlucas/phpdotenv/src/Dotenv.php(50): Dotenv\Dotenv->loadData() #6 /var/munkireport/app/helpers/config_helper.php(16): Dotenv\Dotenv->load() #7 /var/munkireport/bootstrap/app.php(35): initDotEnv() #8 /var/munk in /var/munkireport/vendor/vlucas/phpdotenv/src/Loader.php on line 262
```

When I add quotes or single quotes, they show up as part of the sitename (as noted in the wiki). I also tried escaping the space and that gives the same error.

When I check the env inside the docker container it has this line, which looks correct to me:

```
SITENAME=Mac Reporting
```

**Comment by nathanperkins** [comment]
I was messing around with this for an hour and it seems to have gone away without any explanation.

**Comment by nathanperkins** [comment]
I haven't had any issues with this since. I can't reproduce anymore so it must have been something on my side.
