### ISSUE TITLE
LDAP Authentication crashes on v4.0.2

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [munkireport/munkireport-php#1223]
Using `AUTH_METHODS="LDAP"` with `DEBUG=TRUE` and trying to login leads to this crash:
```
Warning: Use of undefined constant APP_PATH - assumed 'APP_PATH' (this will throw an Error in a future version of PHP) in /var/www/munkireport/current-release/app/lib/munkireport/AuthLDAP.php on line 20

Warning: include_once(APP_PATH/lib/authLDAP/authLDAP.php): failed to open stream: No such file or directory in /var/www/munkireport/current-release/app/lib/munkireport/AuthLDAP.php on line 20

Warning: include_once(): Failed opening 'APP_PATH/lib/authLDAP/authLDAP.php' for inclusion (include_path='.:/usr/share/php') in /var/www/munkireport/current-release/app/lib/munkireport/AuthLDAP.php on line 20

Fatal error: Uncaught Error: Class 'Auth_ldap' not found in /var/www/munkireport/current-release/app/lib/munkireport/AuthLDAP.php:21 
Stack trace: 
#0 /var/www/munkireport/current-release/app/lib/munkireport/AuthHandler.php(54): munkireport\lib\AuthLDAP->login('name', 'abc') 
#1 /var/www/munkireport/current-release/app/lib/munkireport/AuthHandler.php(34): munkireport\lib\AuthHandler->validate('name', 'abc') 
#2 /var/www/munkireport/current-release/app/controllers/auth.php(80): munkireport\lib\AuthHandler->login('name', 'abc') 
#3 /var/www/munkireport/current-release/system/kissmvc_core.php(88): munkireport\controller\Auth->login() 
#4 /var/www/munkireport/current-release/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') 
#5 /var/www/munkireport/current-release/bootstrap/app.php(121): Engine->__construct(Array, 'show', 'index', 'AUTO') 
#6 /var/www/munkireport/current-release/public/index.php(7): require_once('/var/www/munkir...') 
#7 { in /var/www/munkireport/current-release/app/lib/munkireport/AuthLDAP.php on line 21
```

**Comment by bochoven** [comment]
Please use the AD_AUTH authentication as described here: https://github.com/munkireport/munkireport-php/wiki/LDAP-Authentication-%28AD%2C-OpenLDAP%2C-FreeIPA%29
