### ISSUE TITLE
index.php?/report/hash_check failed

### ISSUE THREAD

**Issue by cdhw2018** [munkireport/munkireport-php#1262]
MunkiReport Version 4.3.2.3838:

I've recently updated my server to Mojave and have migrated the websites from Server.app to Apache2. The munkireport dashboard is working fine via port 8443:

  https://FQDN:8443/munkireports/index.php?/system/show/status

as is Munki itself. Version 4.3.2 of the client, however, is failing with an error message in the Munki log:

    Finishing...
        Performing postflight tasks...
        postflight stderr: ERROR: Munkireport:   https://FQDN:8443/munkireports/index.php?/report/hash_check failed, HTTP returncode 500 (internal server error)
   Done.

The apache log doesn't contain anything useful:

default xxx.xxx.xxx.xxx - - [20/Jul/2019:01:07:19 +0100] "POST /munkireports/index.php?/report/hash_check HTTP/1.1" 500 - "-" "Python/2.7.10 CFNetwork/978.0.7 Darwin/18.6.0 (x86_64)"

and connecting to

    https://FQDN:8443/munkireports/index.php?/report/hash_check

with a browser returns:

    a:1:{s:5:"error";s:17:"Serial is missing";}

When I enable 'DEBUG=TRUE' in .env the client gives more information:

Finishing...
    Performing postflight tasks...
    postflight stderr: ERROR: Munkireport: Could not unserialize server data: Next is `b` not `:` in ...<b --> r <--  />
<b>Fatal error</b>:  Uncaught Error: Call to ...
ERROR: Munkireport: Request: {'items': 'a:47:{s:8:"warranty";a:1:{s:4:"hash";s:32:"fefe0e6be97b44964dbb210f841b4b47";}s:14:"installhistory";a:1:{s:4:"hash";s:32:"31f6c100b6b36d4536e1775f5656624f";}s:5:"fonts";a:1:{s:4:"hash";s:32:"6eaaf946d0f7ff6485c2b0a8b98800f7";}s:10:"reportdata";a:1:{s:4:"hash";s:32:"87fce47c6234253838932bb604e8fceb";}s:8:"appusage";a:1:{s:4:"hash";s:32:"b7cadbe82a2382cbea6e1e5f353eeb76";}s:9:"bluetooth";a:1:{s:4:"hash";s:32:"827fc3b41f7683184fa2e283207ac059";}s:13:"displays_info";a:1:{s:4:"hash";s:32:"61b1308f6c473be00d6bcddf6faca066";}s:12:"supported_os";a:1:{s:4:"hash";s:32:"dafd8f322e27487440316779b9252fa4";}s:3:"ard";a:1:{s:4:"hash";s:32:"076bef2f939bf7a945f9b55aa91a3714";}s:13:"servermetrics";a:1:{s:4:"hash";s:10:"NOT A FILE";}s:10:"localadmin";a:1:{s:4:"hash";s:32:"bd1c98b5789fc4f515908b917212c4bc";}s:8:"devtools";a:1:{s:4:"hash";s:32:"45434a873766ba447a1c0ed8529b4876";}s:11:"timemachine";a:1:{s:4:"hash";s:32:"acb9d5b73d39a9945de52ca3fdfb80ff";}s:7:"machine";a:1:{s:4:"hash";s:32:"3246e0a7d76fd9c70ed971424198d0c3";}s:9:"findmymac";a:1:{s:4:"hash";s:32:"53a450534e20192b16a58ae4c3af31fa";}s:7:"service";a:1:{s:4:"hash";s:32:"d41d8cd98f00b204e9800998ecf8427e";}s:11:"disk_report";a:1:{s:4:"hash";s:32:"fc56bd473c3a62dec7390db84addb7da";}s:16:"filevault_escrow";a:1:{s:4:"hash";s:10:"NOT A FILE";}s:15:"managedinstalls";a:1:{s:4:"hash";s:32:"3f35b874049f5e3eb98524b6786ebe47";}s:8:"location";a:1:{s:4:"hash";s:32:"6ea9a4de3c5522a26e70507e6273947c";}s:3:"gpu";a:1:{s:4:"hash";s:32:"c239de39604ee2ea77f283208bdaf089";}s:17:"directory_service";a:1:{s:4:"hash";s:32:"c4da3d5c8f6758ee96ef3ca5cab43dea";}s:11:"munkireport";a:1:{s:4:"hash";s:32:"1f1dd7f10940f3e2c0356b6ab8c0ccb5";}s:7:"profile";a:1:{s:4:"hash";s:32:"8bddcaacb6e1d64ea0dd7cfeacd3d083";}s:7:"printer";a:1:{s:4:"hash";s:32:"285229add2d1bded11bb4f2f273db79e";}s:9:"fan_temps";a:1:{s:4:"hash";s:32:"443bb827beb02afd62f6a0eba932a3c5";}s:15:"munkireportinfo";a:1:{s:4:"hash";s:32:"893680d3c2cddf7f2e5a78ab306d7af8";}s:9:"munkiinfo";a:1:{s:4:"hash";s:32:"9efc1211bfa5c88cbc8bdef1fb51aef3";}s:13:"user_sessions";a:1:{s:4:"hash";s:32:"4962bc21f082b84e0b2608d1ee3558f8";}s:12:"applications";a:1:{s:4:"hash";s:32:"322eb8881a1c794d6be579f0eb822155";}s:14:"softwareupdate";a:1:{s:4:"hash";s:32:"c395dcfa31b60bd4cfccad8881c0f50a";}s:16:"filevault_status";a:1:{s:4:"hash";s:32:"3dc8a43ae23c197565235d8c56b38a57";}s:5:"power";a:1:{s:4:"hash";s:32:"c81f3f49e60180131daa850985bbbe50";}s:11:"sccm_status";a:1:{s:4:"hash";s:32:"e8fa125cf6a3d5bbd84f84d71a0a7aea";}s:14:"network_shares";a:1:{s:4:"hash";s:32:"f308e3300cac8c7a7a95cb0e2cd37504";}s:11:"certificate";a:1:{s:4:"hash";s:32:"da0a5685371d4bac2aea32899daa50d2";}s:9:"inventory";a:1:{s:4:"hash";s:32:"d26d907b5587718016226bb9ccbed52d";}s:4:"wifi";a:1:{s:4:"hash";s:32:"1c7da8a629d5b9fd517793ea117ae64c";}s:11:"mbbr_status";a:1:{s:4:"hash";s:10:"NOT A FILE";}s:7:"network";a:1:{s:4:"hash";s:32:"6ed6aba001f8c7b168bd123010a3bd91";}s:11:"usage_stats";a:1:{s:4:"hash";s:32:"400e6855763b5fb49dee0ba8f9a9d136";}s:10:"mdm_status";a:1:{s:4:"hash";s:32:"45127b0644dfeafdc5492df7f5f582ca";}s:10:"extensions";a:1:{s:4:"hash";s:32:"470447f037cf4bcadf82730ada004328";}s:3:"usb";a:1:{s:4:"hash";s:32:"e851e8027113af6aa1b396033d96a9ce";}s:7:"caching";a:1:{s:4:"hash";s:32:"c552d6c6812ba18ee4750df7247e4f9c";}s:8:"security";a:1:{s:4:"hash";s:32:"7bf92482223e98fed061c59f60dac3bf";}s:11:"munki_facts";a:1:{s:4:"hash";s:32:"6c19cd4cf1bc91b759f42a1437c65256";}}', 'serial': u'DGKV1HD1H7VF', 'passphrase': None}
ERROR: Munkireport: Response: <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method Reportdata_model::updateOrCreate() in /Users/Shared/munki/munkireport-php/app/controllers/report.php:346
Stack trace:
#0 /Users/Shared/munki/munkireport-php/app/controllers/report.php(80): munkireport\controller\report-&gt;_register('DGKV1HD1H7VF')
#1 /Users/Shared/munki/munkireport-php/system/kissmvc_core.php(88): munkireport\controller\report-&gt;hash_check()
#2 /Users/Shared/munki/munkireport-php/system/kissmvc.php(17): KISS_Engine-&gt;__construct(Array, 'show', 'index', 'AUTO')
#3 /Users/Shared/munki/munkireport-php/bootstrap/app.php(121): Engine-&gt;__construct(Array, 'show', 'index', 'AUTO')
#4 /Users/Shared/munki/munkireport-php/public/index.php(7): require_once('/Users/Shared/m...')
#5 {main}
  thrown in <b>/Users/Shared/munki/munkireport-php/app/controllers/report.php</b> on line <b>346</b><br />
Done.
sh-3.2# 

What steps do I need to take to try and pin down the problem, which I suspect is a bug in 4.3.2 but maybe I've missed something.

TIA

Charles

**Comment by cdhw2018** [comment]
Now fixed. Issue was this message:

"Fatal error: Uncaught Error: Call to undefined method Reportdata_model::updateOrCreate() in /Users/Shared/munki/munkireport-php/app/controllers/report.php:346

which after some sleuthing turned out to be the 'eloquent' package needing an update, which is handled by 'composer'. Re-running

    php composer update --no-dev

fixed it.
