### ISSUE TITLE
Migration to 5.8.0: 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

### ISSUE THREAD

**Issue by doits** [munkireport/munkireport-php#1513]
When upgrading I git this error running the migrations:

```
$ ./please migrate
Migrating: 2023_02_28_000000_inventory_bigint_id
PHP Fatal error:  Uncaught Error: Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found in /var/www/munkireport-php/vendor/illuminate/database/MySqlConnection.php:64
Stack trace:
#0 /var/www/munkireport-php/vendor/illuminate/database/Connection.php(894): Illuminate\Database\MySqlConnection->getDoctrineDriver()
#1 /var/www/munkireport-php/vendor/illuminate/database/Schema/Grammars/ChangeColumn.php(36): Illuminate\Database\Connection->getDoctrineSchemaManager()
#2 /var/www/munkireport-php/vendor/illuminate/database/Schema/Grammars/Grammar.php(55): Illuminate\Database\Schema\Grammars\ChangeColumn::compile()
#3 /var/www/munkireport-php/vendor/illuminate/database/Schema/Blueprint.php(128): Illuminate\Database\Schema\Grammars\Grammar->compileChange()
#4 /var/www/munkireport-php/vendor/illuminate/database/Schema/Blueprint.php(101): Illuminate\Database\Schema\Blueprint->toSql()
#5 /var/www/munkireport-php/vendor/illuminate/database/Schema/Builder.php(290): Illuminate\Database\Schema\Blueprint->build()
#6 /var/www/munkireport-php/vend in /var/www/munkireport-php/vendor/illuminate/database/MySqlConnection.php on line 64
```

Changing `composer.json` to require an older `doctrine/dbal` fixes it:

```diff
diff --git a/composer.json b/composer.json
index 311764a3..fa31fd10 100644
--- a/composer.json
+++ b/composer.json
@@ -77,7 +77,7 @@
     "fakerphp/faker": "^1.13",
     "guzzlehttp/guzzle": "~7.0",
     "munkireport/usb": "^3.0",
-    "doctrine/dbal": "~3.6",
+    "doctrine/dbal": "~2.3",
     "munkireport/sentinelone": "^3.0",
     "munkireport/inventory": "^7.0",
     "adldap2/adldap2": "^10",
```

Looks like the migration is not compatible with newer `dbal`?

I reverted the change after the migrations completed, but I'm not sure what should be the correct version in the end.

**Comment by bochoven** [comment]
Is your server running php 8.x?

**Comment by doits** [comment]
Aah probably it is because `illumniate/database` is incompatible with `dbal` `3` ... it installs `v7.30.6` for me, probably the later versions are not compatible with php `7`.

**Comment by doits** [comment]
Seems to be only supported from `v8.15.0` onwards, see https://github.com/laravel/framework/releases/tag/v8.15.0

> Added Support DBAL v3.0 (https://github.com/laravel/framework/pull/35236)

**Comment by bochoven** [comment]
I don't think we want to keep supporting EOL versions of PHP, so I'm closing this issue. I think we need to update the docs so it's clear that PHP 7 is not supported anymore in MunkiReport 5.8
