### ISSUE TITLE
Issue with Laravel 10.17

### ISSUE THREAD

**Issue by tuxudo** [munkireport/munkireport-php#1529]
Starting with Laravel 10.17, there is an issue when calling `php please migrate`. Fix is to version lock `illuminate/console`, `illuminate/database`, `illuminate/events`,  and `illuminate/filesystem` to 10.16 until bug is fixed upstream.

Error is: ```Fatal error: Uncaught Error: Call to undefined method Illuminate\Container\Container::runningUnitTests() in /var/munkireport/vendor/illuminate/console/Concerns/ConfiguresPrompts.php:27
Stack trace:
#0 /var/munkireport/vendor/illuminate/console/Command.php(177): Illuminate\Console\Command->configurePrompts(Object(Symfony\Component\Console\Input\ArgvInput))
#1 /var/munkireport/vendor/symfony/console/Application.php(1063): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/munkireport/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/munkireport/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/munkireport/please(39): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /var/munkireport/vendor/illuminate/console/Concerns/ConfiguresPrompts.php on line 27```

**Comment by sphen13** [comment]
in discussing this further with @tuxudo we saw that other illuminate dependencies were installing 10.17+. to resolve this in case the version mismatch causes issues i expanded the change with this commit https://github.com/sphen13/munkireport-php/commit/3c67fe3806fd497e67a80cee1d67ad25b3a8f893 - i could PR That if desired or @tuxudo could decide to update this one perhaps.

**Comment by tuxudo** [comment]
This also breaks Module Marketplace as discovered by @jbaker10

**Comment by jby** [comment]
> This also breaks Module Marketplace as discovered by @jbaker10

Or rather @jby, i.e. me... ;)

**Comment by SamdyPrum** [comment]
Hello All!

I got a problem with run **./please migrate**

```

PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Container\Container::runningUnitTests() in /usr/share/nginx/html/report/vendor/illuminate/console/Concerns/ConfiguresPrompts.php:30
Stack trace:
#0 /usr/share/nginx/html/report/vendor/illuminate/console/Command.php(177): Illuminate\Console\Command->configurePrompts()
#1 /usr/share/nginx/html/report/vendor/symfony/console/Application.php(1063): Illuminate\Console\Command->run()
#2 /usr/share/nginx/html/report/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#3 /usr/share/nginx/html/report/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#4 /usr/share/nginx/html/report/please(39): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /usr/share/nginx/html/report/vendor/illuminate/console/Concerns/ConfiguresPrompts.php on line 30
```

If anyone know how to fix it let know, thank you!

**Comment by sphen13** [comment]
@SamdyPrum we limited laravel to 10.16 to address this for now - was pushed via this commit - are you up to date? https://github.com/munkireport/munkireport-php/pull/1531

**Comment by SamdyPrum** [comment]
@sphen13 It's worked 
Thank you!

**Comment by tuxudo** [comment]
Fixed in `5.x` branch, will properly fix in next MR release.
